# ./.github/workflows/releasedcontainerimage.yaml

name: Released Container Image
on:
  release:
    types: [published, released, edited]
jobs:
  build-and-push:
    name: Build and push to quay.io
    runs-on: ubuntu-latest 
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: Get the release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build and push container images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: quay.io
          repository: redhatgov/sre-workshop-dashboard
          tags: ${{ steps.get_version.outputs.VERSION }}
          add_git_labels: true
